### PR TITLE
feat: upload entire 400 proteins script

### PR DESCRIPTION
**Pull request by xnought**
# #90

https://github.com/xnought/venome/assets/65095341/35e4a3ae-9c62-4680-9643-f48e44d57761

- command to add all proteins
- command to delete all proteins 

See the run.md docs

### CODE REVIEW

**Comment by ansengarvin** [comment]
Upload script works!

Only issue I had was in run.md - "python3" command doesn't work for me (Windows), but I was able to get it to work by substituting it with "py".

**Comment by xnought** [comment]
Awesome thank you!

**Comment by xnought** [comment]
@ansengarvin Can you alias py to python3? Or install python3 somehow so in the future the script always works.

**Comment by ansengarvin** [comment]
I'll look into it! For now, I think it's fine to merge.

**Pull request merged**
